homepage:
  path: /profile/
  defaults:
    _controller: Nucleos\ProfileBundle\Action\ShowProfileAction

redirect_to_admin:
  path: /
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    route: nucleos_profile_profile_show
    permanent: false
