<?php

namespace AppBundle\Entity;

use AppBundle\BaseTest;
use AppBundle\Entity\Cart\Cart;
use AppBundle\Entity\Cart\CartItem;
use AppBundle\Entity\Menu\MenuItem;
use AppBundle\Utils\ValidationUtils;
use AppBundle\Validator\Constraints\DeliveryDateInFuture;
use Carbon\Carbon;

class OrderTest extends BaseTest
{
    private $validator;

    public function setUp()
    {
        parent::setUp();

        $this->validator = static::$kernel->getContainer()->get('validator');

        Carbon::setTestNow(Carbon::create(2017, 9, 2, 11, 0));
    }

    protected function tearDown()
    {
        Carbon::setTestNow();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testAddCartItem()
    {
        $order = new Order();
        $cart = new Cart();

        $pizza = new MenuItem();
        $pizza
            ->setName('Pizza')
            ->setPrice(10);

        $salad = new MenuItem();
        $salad
            ->setName('Salad')
            ->setPrice(5);

        $pizzaItem = new CartItem($cart, $pizza, 4);
        $order->addCartItem($pizzaItem, $pizza);

        $saladItem = new CartItem($cart, $salad, 2);
        $order->addCartItem($saladItem, $salad);

        $this->assertCount(2, $order->getOrderedItem());

        $pizzaItem = $order->getOrderedItem()->filter(function (OrderItem $orderItem) use ($pizza) {
            return $orderItem->getMenuItem() === $pizza;
        })->first();

        $saladItem = $order->getOrderedItem()->filter(function (OrderItem $orderItem) use ($salad) {
            return $orderItem->getMenuItem() === $salad;
        })->first();


        $this->assertEquals(4, $pizzaItem->getQuantity());
        $this->assertEquals(2, $saladItem->getQuantity());
    }

    public function testTotal()
    {
        $order = new Order();
        $cart = new Cart();

        $pizza = new MenuItem();
        $pizza
            ->setName('Pizza')
            ->setPrice(10);

        $salad = new MenuItem();
        $salad
            ->setName('Salad')
            ->setPrice(5);

        $pizzaItem = new CartItem($cart, $pizza, 4);
        $order->addCartItem($pizzaItem, $pizza);

        $saladItem = new CartItem($cart, $salad, 2);
        $order->addCartItem($saladItem, $salad);

        $this->assertEquals(5000, $order->getTotal());
    }
}
