fos_js_routing:
    cache_control:
        public: true
        maxage: 600
        smaxage: 600
        expires: '10 minutes'
        vary:
            - Accept-Encoding
    routes_to_expose:
        - ^restaurant$
        - ^restaurants$
        - restaurant_remove_from_cart
        - restaurant_cart_address
        - restaurant_cart_clear_time
        - restaurant_modify_cart_item_quantity
        - admin_deliveries
        - admin_delivery
        - admin_deliveries_pricing_ruleset
        - admin_store_delivery_new
        - admin_dashboard_fullscreen
        - admin_foodtech_dashboard
        - admin_foodtech_settings
        - admin_form
        - admin_incident
        - admin_metrics
        - admin_order
        - admin_order_edit
        - admin_order_accept
        - admin_order_refuse
        - admin_order_cancel
        - admin_order_delay
        - admin_order_fulfill
        - admin_restaurant
        - admin_store
        - admin_restaurant_dashboard
        - admin_restaurant_image_from_url
        - admin_restaurant_stats
        - admin_business_restaurant_group
        - admin_tags
        - admin_task_image_download
        - admin_task_list_create
        - admin_task_receipt
        - admin_transporter_message
        - admin_users_search
        - admin_user_edit
        - admin_vehicles
        - order_continue
        - profile_jwt
        - profile_notifications
        - profile_notifications_mark_as_read
        - profile_notifications_remove
        - profile_notification_remove
        - dashboard_order_accept
        - dashboard_order_refuse
        - dashboard_order_cancel
        - dashboard_order_delay
        - dashboard_order_fulfill
        - dashboard_restaurant_dashboard
        - dashboard_restaurant_image_from_url
        - dashboard_restaurant_stats
        - routing_route
        - user_avatar
        - dashboard_restaurant_new_adhoc_order
        - public_share_order
        - order_set_guest_customer_email
        - _api_/orders/{id}/players_post
        - _api_/orders/{id}/create_invitation_post
        - _api_/incidents/{id}/comments_post
        - _api_/incidents/{id}/action_put
        - _api_/tasks/{id}/failure_reasons_get
        - _api_/incident_images{._format}_post
        - _api_/incidents/{id}{._format}_patch
        - _api_/incidents{._format}_get_collection
        - _api_/tasks/{id}/context_get
        - _api_/tasks{._format}_get_collection
        - _api_/tours{._format}_get_collection
        - _api_/task_lists/v2_get_collection
        - _api_/task_lists/set_items/{date}/{username}_put
        - _api_/stores{._format}_get_collection
        - _api_/stores/{id}{._format}_delete
        - _api_/stores/{id}{._format}_patch
        - _api_/restaurants/{id}{._format}_delete
        - _api_/delivery_forms/{id}{._format}_delete
        - _api_/pricing_rule_sets/{id}{._format}_delete
        - _api_/pricing_rule_sets/{id}/applications_get
        - _api_/package_sets/{id}{._format}_delete
        - _api_/package_sets/{id}/applications_get
        - _api_/time_slots/{id}{._format}_delete
        - _api_/organizations{._format}_get_collection
        - _api_/time_slots{._format}_get_collection
        - _api_/warehouses{._format}_post
        - _api_/warehouses{._format}_get_collection
        - _api_/warehouses/{id}{._format}_delete
        - _api_/trailers{._format}_post
        - _api_/trailers{._format}_get_collection
        - _api_/trailers/{id}{._format}_delete
        - _api_/vehicles{._format}_post
        - _api_/vehicles{._format}_get_collection
        - _api_/vehicles/{id}{._format}_delete
        - admin_warehouses
        - _api_/task_lists/{id}{._format}_patch
        - _api_/vehicles/{id}{._format}_patch
        - _api_/trailers/{id}{._format}_patch
        - _api_/trailers/{id}/vehicles_put
        - task_label_pdf
        - _api_/stores/{id}/deliveries_get_collection
        - _api_/deliveries/pod_export_post
