fos_js_routing:
    cache_control:
        public: true
        maxage: 600
        smaxage: 600
        expires: '10 minutes'
        vary:
            - Accept-Encoding
    routes_to_expose:
        - ^restaurant$
        - ^restaurants$
        - restaurant_remove_from_cart
        - restaurant_cart_address
        - restaurant_cart_clear_time
        - restaurant_modify_cart_item_quantity
        - admin_deliveries
        - admin_delivery
        - admin_dashboard_fullscreen
        - admin_foodtech_dashboard
        - admin_foodtech_settings
        - admin_form
        - admin_metrics
        - admin_order
        - admin_order_edit
        - admin_order_accept
        - admin_order_refuse
        - admin_order_cancel
        - admin_order_delay
        - admin_order_fulfill
        - admin_restaurant
        - admin_store
        - admin_restaurant_dashboard
        - admin_restaurant_image_from_url
        - admin_restaurant_stats
        - admin_business_restaurant_group
        - admin_tags
        - admin_task_image_download
        - admin_task_list_create
        - admin_task_receipt
        - admin_users_search
        - admin_user_edit
        - admin_vehicles
        - order_continue
        - profile_jwt
        - profile_notifications
        - profile_notifications_mark_as_read
        - profile_notifications_remove
        - profile_notification_remove
        - dashboard_order_accept
        - dashboard_order_refuse
        - dashboard_order_cancel
        - dashboard_order_delay
        - dashboard_order_fulfill
        - dashboard_restaurant_dashboard
        - dashboard_restaurant_image_from_url
        - dashboard_restaurant_stats
        - routing_route
        - user_avatar
        - dashboard_restaurant_new_adhoc_order
        - public_share_order
        - order_set_guest_customer_email
        - api_orders_add_player_item
        - api_orders_create_invitation_item
        - api_orders_get_cart_timing_item
        - api_orders_validate_item
        - api_incidents_add_comment_item
        - api_incidents_action_item
        - api_tasks_task_failure_reasons_item
        - api_incident_images_post_collection
        - api_incidents_get_item
        - api_incidents_get_collection
        - api_tasks_get_task_context_item
        - api_tasks_get_collection
        - api_tours_get_collection
        - api_task_lists_v2_collection
        - api_task_lists_set_items_item
        - admin_incident
        - api_stores_get_item
        - api_restaurants_get_item
        - api_stores_delete_item
        - api_restaurants_delete_item
        - api_delivery_forms_delete_item
        - api_pricing_rule_sets_delete_item
        - api_pricing_rule_sets_applications_item
        - api_package_sets_delete_item
        - api_package_sets_applications_item
        - api_time_slots_delete_item
        - admin_transporter_message
        - api_organizations_get_collection
        - api_time_slots_get_collection
        - api_warehouses_post_collection
        - api_warehouses_get_collection
        - api_warehouses_delete_item
        - api_trailers_post_collection
        - api_trailers_get_collection
        - api_trailers_delete_item
        - api_vehicles_post_collection
        - api_vehicles_get_collection
        - api_vehicles_delete_item
        - admin_warehouses
        - api_task_lists_patch_item
        - api_vehicles_patch_item
        - api_trailers_patch_item
        - api_trailers_set_vehicles_item
        - task_label_pdf
