version: '3'

services:

  webpack:
    volumes:
      - 'node_modules:/srv/coopcycle/node_modules'
      - 'webpack-sync:/srv/coopcycle:nocopy'

  php:
    volumes:
      - 'php_session:/srv/coopcycle/var/sessions'
      - 'php_vendor:/srv/coopcycle/vendor'
      - 'php-sync:/srv/coopcycle:nocopy'

volumes:
    php-sync:
      external: true
    webpack-sync:
      external: true
    php_vendor:
    php_session: