apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: api-platform

profiles:
  - name: dev
    activation:
      - kubeContext: minikube
        command: dev
    build:
      artifacts:
        - image: coopcycle-web
          context: .
          docker:
            dockerfile: ./docker/php/Dockerfile
            target: frankenphp_prod
        - image: osrm
          context: ./docker/osrm
    deploy:
      # a workaround for some services depending on others and failing before the others are ready
      # for example, the centrifugo's dependency on redis
      tolerateFailuresUntilDeadline: true
      helm:
        releases:
          - name: coopcycle-platform
            chartPath: ./helm/coopcycle-platform
            #wait: true
            #valuesFiles:
            #- helm-skaffold-values.yaml
            skipBuildDependencies: true # Skip helm dep build
            #recreatePods will pass --recreate-pods to helm upgrade
            #recreatePods: true
            #overrides builds an override values.yaml file to run with the helm deploy
            #overrides:
            # some:
            #   key: someValue
            #setValues get appended to the helm deploy with --set.
            #setValues:
            # some:
            #   key: someValue
            namespace: default
            # IMPORTANT: To get Skaffold to work with Helm, the image key must be configured in the skaffold.yaml.
            setValueTemplates:
              osrm.image.repository: "{{.IMAGE_REPO_osrm}}"
              osrm.image.tag: "{{.IMAGE_TAG_osrm}}@{{.IMAGE_DIGEST_osrm}}"
              php.image.repository: "{{.IMAGE_REPO_coopcycle_web}}"
              php.image.tag: "{{.IMAGE_TAG_coopcycle_web}}@{{.IMAGE_DIGEST_coopcycle_web}}"
            valuesFiles:
              - skaffold-values-dev.yaml
