afghan: circle-flags:af
african: academicons:africarxiv
albanian: circle-flags:al
algerian: emojione:flag-for-algeria
alsatian: noto:pretzel
american: circle-flags:us
andalusian: noto:olive
aragonese: circle-flags:es-ar
argentine: emojione:flag-for-argentina
armenian: circle-flags:am
asian: twemoji:steaming-bowl
asturian: noto:octopus
australian: circle-flags:au
austrian: circle-flags:at
auvergne: noto:cheese-wedge
bagels: noto:bagel
bakery: noto:croissant
bangladeshi: circle-flags:bd
barbecue: noto:cut-of-meat
basque: circle-flags:es-pv
belgian: emojione:flag-for-belgium
bento: noto-v1:bento-box
bistro: noto-v1:wine-glass
brazilian: emojione:flag-for-brazil
british: circle-flags:gb
burgers: twemoji:hamburger
burgundy: noto:wine-glass
burmese: circle-flags:mm
cafe: streamline-kameleon-color:coffee-paper-glass
cajun: noto:hot-pepper
californian: circle-flags:us-ca
calzones: noto:stuffed-flatbread
cambodian: circle-flags:kh
canadian: circle-flags:ca
canary: circle-flags:ic
caribbean: noto:tropical-drink
castiza: noto:squid
catalan: circle-flags:es-ct
cheesesteaks: noto:cheese-wedge
chicken: emojione:chicken
chilean: circle-flags:cl
chinese: emojione:flag-for-china
chowder: noto:pot-of-food
coffee: streamline-kameleon-color:coffee-paper-glass
colombian: emojione:flag-for-colombia
contemporary: noto:fork-and-knife-with-plate
continental: noto:fork-and-knife-with-plate
corsica: noto:chestnut
creole: noto:crab
crepes: noto:pancakes
cuban: circle-flags:cu
czech: circle-flags:cz
deli: noto:bread
dim_sum: noto:dumpling
diner: noto:fork-and-knife-with-plate
dominican: circle-flags:do
donuts: token-branded:donut
dutch: circle-flags:nl
eastern_european: noto:dumpling
eclectic: noto:fork-and-knife-with-plate
ecuadorean: circle-flags:ec
egyptian: circle-flags:eg
english: circle-flags:lang-en
ethiopian: circle-flags:et
european: emojione:flag-for-european-union
extremaduran: noto:pig
fast_food: twemoji:french-fries
filipino: circle-flags:ph
fish_and_chips: noto:fish
fondue: noto:fondue
french: emojione:flag-for-france
frozen_yogurt: noto:soft-ice-cream
fusion: noto:fork-and-knife-with-plate
galician: circle-flags:es-ga
gastronomic: streamline-sharp:chef-toque-hat
gastropub: noto:beer-mug
german: circle-flags:de
gluten_free: healthicons:gluten-free-outline
greek: emojione:flag-for-greece
grill: noto:cut-of-meat
gyros: noto:stuffed-flatbread
haitian: circle-flags:ht
halal: hugeicons:halal
hand_made: noto:raised-hand
hawaiian: fxemoji:palmtree
healthy: noto:red-apple
home_made: streamline-emojis:woman-cook-2
hot_dogs: noto:hot-dog
ice_cream: noto:ice-cream
indian: emojione:flag-for-india
indonesian: circle-flags:id
international: glyphs-poly:globe-west
irish: circle-flags:ie
israeli: circle-flags:il
italian: fxemoji:italianflag
jamaican: circle-flags:jm
japanese: emojione:flag-for-japan
juices: noto:beverage-box
kebab: noto:taco
korean_barbeque: circle-flags:kr
korean: circle-flags:kr
kosher: emojione:star-of-david
latin_american: noto:ear-of-corn
latin: noto:tamale
lebanese: emojione:flag-for-lebanon
levantine: noto:falafel
local: glyphs-poly:map-marker-line
lyonnais: noto:pot-of-food
malaysian: circle-flags:my
manchega: noto:cheese-wedge
mediterranean: noto:shallow-pan-of-food
mexican: emojione:flag-for-mexico
middle_eastern: noto:falafel
mongolian: circle-flags:mn
moroccan: circle-flags:ma
nepalese: circle-flags:np
noodle_bar: noto:steaming-bowl
norwegian: circle-flags:no
organic: noto:herb
oysters: noto:oyster
pacific_rim: noto:tropical-fish
pakistani: circle-flags:pk
pan_asian: noto:steaming-bowl
pasta: noto:spaghetti
pastries: twemoji:shortcake
persian: circle-flags:ir
peruvian: circle-flags:pe
pho: emojione:steaming-bowl
pizza: noto:pizza
plant_based: noto:broccoli
poke_bowl: fluent-emoji-flat:green-salad
polish: circle-flags:pl
polynesian: noto:coconut
portuguese: circle-flags:pt
provencal: noto:sunflower
pub_food: noto:beer-mug
puerto_rican: circle-flags:pr
raw: noto:carrot
ribs: noto:meat-on-bone
rice_based: twemoji:taco
russian: circle-flags:ru
salad: twemoji:green-salad
salvadoran: circle-flags:sv
sandwiches: noto:sandwich
savoy: noto:fondue
scandinavian: noto:fish
seafood: noto:shrimp
senegalese: circle-flags:sn
singaporean: circle-flags:sg
smoothies: noto:cup-with-straw
soul_food: noto:bacon
soup: twemoji:bowl-with-spoon
south_african: circle-flags:za
south_american: noto:avocado
southern: noto:fried-shrimp
south_pacific: noto:tropical-fish
southwestern: noto:cactus
spanish: emojione:flag-for-spain
steak: twemoji:cut-of-meat
steakhouse: twemoji:cut-of-meat
steetfood: fluent-emoji-flat:cityscape-at-dusk
subs: noto:baguette-bread
sushi: twemoji:sushi
taiwanese: circle-flags:tw
tapas: noto:woman-dancing
tea: emojione:teacup-without-handle
tex_mex: emojione:flag-for-mexico
thai: emojione:flag-for-thailand
tibetan: noto:snow-capped-mountain
traditional: noto:fork-and-knife-with-plate
tunisian: circle-flags:tn
turkish: circle-flags:tr
ukrainian: circle-flags:ua
vegan: lucide:vegan
vegetarian: noto:seedling
venezuelan: emojione:flag-for-venezuela
vietnamese: emojione:flag-for-vietnam
wings: noto:poultry-leg
wraps: noto:burrito
