LSP53:
  address_name: Centre logistique Proximus
  street_name: "Rue du Nord Belge 6, 4020 Liège, Belgique"

T527:
  address_name: Shop Proximus Rocourt
  street_name: "Chaussée de Tongres 269, 4000 Liège, Belgique"

B536:
  address_name: Shop Proximus Vinâve d'Île
  street_name: "Rue Vinâve d'Île 36/38, 4000 Liège, Belgique"

T529:
  address_name: Shop Proximus Belle-Ile
  street_name: "Quai des Vennes 1, Liège, Belgique"

T782:
  address_name: Shop Proximus Médiacité
  street_name: "Rue Grétry 74, 4020 Liège, Belgique"
