AppBundle\Entity\TaskCollectionItem:
    type: entity
    table: task_collection_item
    uniqueConstraints:
        task_collection_item_unique:
            columns:
                - parent_id
                - task_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        position:
            type: integer
    manyToOne:
        parent:
            targetEntity: AppBundle\Entity\TaskCollection
            fetch: LAZY
            inversedBy: items
            joinColumns:
                parent_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        task:
            targetEntity: AppBundle\Entity\Task
            cascade:
                - persist
            fetch: LAZY
            joinColumns:
                task_id:
                    referencedColumnName: id
