Feature: Tasks lists
  Scenario: Assign tasks and tours with PUT and retrieve tasks in the app
    Given the fixtures files are loaded:
      | sylius_channels.yml |
      | tasks.yml        |
      | users.yml        |
    And the user "bob" has role "ROLE_DISPATCHER"
    And the user "bob" is authenticated
    When I add "Content-Type" header equal to "application/ld+json"
    And I add "Accept" header equal to "application/ld+json"
    And the user "bob" sends a "PUT" request to "/api/task_lists/set_items/2018-03-02/bob" with body:
    """
    {"items" : ["/api/tasks/4", "/api/tours/1"]}
    """
    Then the response status code should be 200
    And the JSON should match:
    """
    {
      "@context":"/api/contexts/TaskList",
      "@id":"/api/task_lists/1",
      "@type":"TaskList",
      "items":["/api/tasks/4","/api/tours/1"],
      "distance":@integer@,
      "duration":@integer@,
      "polyline":"@string@",
      "createdAt":"@string@.isDateTime()",
      "updatedAt":"@string@.isDateTime()",
      "date":"2018-03-02",
      "username":"bob"
    }
    """
    And the user "bob" sends a "GET" request to "/api/me/tasks/2018-03-02"
    Then print last response
    Then the response status code should be 200
    And the response should be in JSON
    And the JSON should match:
    """
      {
        "@context":"/api/contexts/TaskList",
        "@id":"/api/task_lists/1",
        "@type":"TaskList",
        "hydra:member":[
          {
            "@id":"@string@.startsWith('/api/tasks')",
            "@type":"Task",
            "id":4,
            "type":"DROPOFF",
            "status":"TODO",
            "address":{"@*@":"@*@"},
            "after":"@string@.isDateTime().startsWith('2018-03-02T11:30:00')",
            "before":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "doneAfter":"@string@.isDateTime().startsWith('2018-03-02T11:30:00')",
            "doneBefore":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "comments":"#bob",
            "updatedAt":"@string@.isDateTime()",
            "isAssigned":true,
            "assignedTo":"bob",
            "previous":null,
            "group":{"@*@":"@*@"},
            "tags":@array@,
            "doorstep":@boolean@,
            "ref":null,
            "recurrenceRule":null,
            "metadata":[],
            "weight":null,
            "hasIncidents": false,
            "incidents": [],
            "orgName":"",
            "images":[],
            "next":null,
            "packages":[],
            "position":0,
            "createdAt":"@string@.isDateTime()"
          },
          {
            "@id":"@string@.startsWith('/api/tasks')",
            "@type":"Task",
            "id":1,
            "type":"DROPOFF",
            "status":"DONE",
            "address":{"@*@":"@*@"},
            "after":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "before":"@string@.isDateTime().startsWith('2018-03-02T12:30:00')",
            "doneAfter":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "doneBefore":"@string@.isDateTime().startsWith('2018-03-02T12:30:00')",
            "comments":"#bob",
            "updatedAt":"@string@.isDateTime()",
            "isAssigned":true,
            "assignedTo":"bob",
            "previous":null,
            "group":null,
            "tags":@array@,
            "doorstep":@boolean@,
            "ref":null,
            "recurrenceRule":null,
            "metadata":[],
            "weight":null,
            "hasIncidents": false,
            "incidents": [],
            "orgName":"",
            "images":[],
            "next":null,
            "packages":[],
            "position":1,
            "createdAt":"@string@.isDateTime()"
          },
          {
            "@id":"@string@.startsWith('/api/tasks')",
            "@type":"Task",
            "id":2,
            "type":"DROPOFF",
            "status":"DONE",
            "address":{"@*@":"@*@"},
            "after":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "before":"@string@.isDateTime().startsWith('2018-03-02T12:30:00')",
            "doneAfter":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "doneBefore":"@string@.isDateTime().startsWith('2018-03-02T12:30:00')",
            "comments":"#bob",
            "updatedAt":"@string@.isDateTime()",
            "isAssigned":true,
            "assignedTo":"bob",
            "previous":null,
            "group":null,
            "tags":@array@,
            "doorstep":@boolean@,
            "ref":null,
            "recurrenceRule":null,
            "metadata":[],
            "weight":null,
            "hasIncidents": false,
            "incidents": [],
            "orgName":"",
            "images":[],
            "next":null,
            "packages":[],
            "position":1,
            "createdAt":"@string@.isDateTime()"
            }
        ],
        "hydra:totalItems": 3,
        "items":[
          {
            "@id":"@string@.startsWith('/api/tasks')",
            "@type":"Task",
            "id":4,
            "type":"DROPOFF",
            "status":"TODO",
            "address":{"@*@":"@*@"},
            "after":"@string@.isDateTime().startsWith('2018-03-02T11:30:00')",
            "before":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "doneAfter":"@string@.isDateTime().startsWith('2018-03-02T11:30:00')",
            "doneBefore":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "comments":"#bob",
            "updatedAt":"@string@.isDateTime()",
            "isAssigned":true,
            "assignedTo":"bob",
            "previous":null,
            "group":{"@*@":"@*@"},
            "tags":@array@,
            "doorstep":@boolean@,
            "ref":null,
            "recurrenceRule":null,
            "metadata":[],
            "weight":null,
            "hasIncidents": false,
            "incidents": [],
            "orgName":"",
            "images":[],
            "next":null,
            "packages":[],
            "position":0,
            "createdAt":"@string@.isDateTime()"
          },
          {
            "@id":"@string@.startsWith('/api/tasks')",
            "@type":"Task",
            "id":1,
            "type":"DROPOFF",
            "status":"DONE",
            "address":{"@*@":"@*@"},
            "after":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "before":"@string@.isDateTime().startsWith('2018-03-02T12:30:00')",
            "doneAfter":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "doneBefore":"@string@.isDateTime().startsWith('2018-03-02T12:30:00')",
            "comments":"#bob",
            "updatedAt":"@string@.isDateTime()",
            "isAssigned":true,
            "assignedTo":"bob",
            "previous":null,
            "group":null,
            "tags":@array@,
            "doorstep":@boolean@,
            "ref":null,
            "recurrenceRule":null,
            "metadata":[],
            "weight":null,
            "hasIncidents": false,
            "incidents": [],
            "orgName":"",
            "images":[],
            "next":null,
            "packages":[],
            "position":1,
            "createdAt":"@string@.isDateTime()"
          },
          {
            "@id":"@string@.startsWith('/api/tasks')",
            "@type":"Task",
            "id":2,
            "type":"DROPOFF",
            "status":"DONE",
            "address":{"@*@":"@*@"},
            "after":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "before":"@string@.isDateTime().startsWith('2018-03-02T12:30:00')",
            "doneAfter":"@string@.isDateTime().startsWith('2018-03-02T12:00:00')",
            "doneBefore":"@string@.isDateTime().startsWith('2018-03-02T12:30:00')",
            "comments":"#bob",
            "updatedAt":"@string@.isDateTime()",
            "isAssigned":true,
            "assignedTo":"bob",
            "previous":null,
            "group":null,
            "tags":@array@,
            "doorstep":@boolean@,
            "ref":null,
            "recurrenceRule":null,
            "metadata":[],
            "weight":null,
            "hasIncidents": false,
            "incidents": [],
            "orgName":"",
            "images":[],
            "next":null,
            "packages":[],
            "position":1,
            "createdAt":"@string@.isDateTime()"
          },
        ],
        "distance":@integer@,
        "duration":@integer@,
        "polyline":@string@,
        "date":"2018-03-02",
        "username":"bob",
        "createdAt":"@string@.isDateTime()",
        "updatedAt":"@string@.isDateTime()"
      }
      """