- hosts: all
  become: yes
  roles:
    - init

- hosts: web
  become: yes
  roles:
    - geerlingguy.php
    - jdauphant.nginx
    - nodejs
    - weareinteractive.pm2

- hosts: db
  become: yes
  roles:
    - ANXS.postgresql
    - DavidWittman.redis
    - redis-tools
    - osrm-docker
