- hosts: all
  become: yes
  roles:
    - init
    # web
    - geerlingguy.php
    - jdauphant.nginx
    - nodejs
    - weareinteractive.pm2
    # db
    - ANXS.postgresql
    # FIXME Failed to reload sysctl: sysctl: permission denied on key 'vm.overcommit_memory
    - DavidWittman.redis
    - redis-tools
    - osrm-docker
